name: Deploy DEV

on:
  push:
    branches: [ dev ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura a chave SSH no ambiente do GitHub Actions
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          log-public-key: false

      # Conecta ao Droplet e executa os comandos de deploy.
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            # Fix git ownership issue
            git config --global --add safe.directory /var/www/dev.gabaritatudo.com.br

            # Navegue para a pasta do seu projeto no servidor
            cd /var/www/dev.gabaritatudo.com.br
            
            # Puxe as últimas alterações do git
            git pull origin dev
            
            chown -R www-data:www-data /var/www/dev.gabaritatudo.com.br
            chmod -R 755 /var/www/dev.gabaritatudo.com.br

            systemctl restart php8.2-fpm
            systemctl restart apache2
            
            echo "Deploy concluído com sucesso! "