name: Deploy DEV

on:
  push:
    branches: [ dev ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/dev.gabaritatudo.com.br
            
            git pull origin dev
            
            systemctl restart php8.2-fpm
            systemctl restart apache2
            
            echo "Deploy concluído com sucesso!"